### ISSUE TITLE
Bug in reference.json concerning text { line-spacing }

### ISSUE THREAD

**Issue by sommerluk** [mapnik/mapnik-reference#124] opened 2016-11-20 19:22 UTC
At https://github.com/mapnik/mapnik/wiki/TextSymbolizer is claimed that line-spacing has the type “double”. And indeed also negative floating point values like “-5.9” seem to work fine and decrease the line hight as expected.

Therefore I guess https://github.com/mapnik/mapnik-reference/blob/77f1902638ff61a4ad6d16f07023ef1042a60500/3.0.6/reference.json#L2125 has to be fixed to allow the usage of negative floating point values also from CartoCSS.

Cross-reference https://github.com/mapbox/carto/issues/452

**Comment by sommerluk** [comment] 2016-11-24 09:41
Also https://github.com/mapnik/mapnik-reference/blob/77f1902638ff61a4ad6d16f07023ef1042a60500/3.0.6/reference.json#L1317 has to be fixed.

**Comment by nebulon42** [comment] 2016-12-11 14:46
Actually duplicate of #56.

**Comment by sommerluk** [comment] 2016-12-11 21:39
This issue applies to both text-line-spacing and shield-line-spacing.

**Closed as completed** 2016-12-22 21:23 UTC
